name: Create Maze
on:
  workflow_dispatch:
    inputs:
      height:
        description: The block height of the maze
        required: false
        default: '50'
        type: string
      width:
        description: The block width of the maze
        required: false
        default: '50'
        type: string
      exportUnsolved:
        description: Export the unsolved maze
        required: false
        default: true
        type: boolean
      exportSolved:
        description: Export the solved maze
        required: false
        default: true
        type: boolean
      printUnsolved:
        description: Print the unsolved maze to the build log
        required: false
        default: true
        type: boolean
      printSolved:
        description: Print the solved maze to the build log
        required: false
        default: true
        type: boolean
      seed:
        description: Seed value to generate a nonrandom maze
        required: false
        default: ''
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - run: python -m pip install --upgrade pip
    - run: python3 -m pip install -r requirements.reqs
    - run: |
        if ${{ inputs.printSolved }}; then
          echo "print_solved=$(echo --print-solved)" >> $GITHUB_ENV
        fi

        if ${{ inputs.printunSolved }}; then
          echo "print_unsolved=$(echo --print-unsolved)" >> $GITHUB_ENV
        fi

        if ${{ inputs.exportUnsolved }}; then
          echo "export-unsolved=$(echo --export-unsolved)" >> $GITHUB_ENV
        fi

        if ${{ inputs.exportSolved }}; then
          echo "export-solved=$(echo --export-solved)" >> $GITHUB_ENV
        fi

        if [[ "${{ inputs.seed }}" != "" ]] ; then
          echo "seed=$(echo --seed=${{inputs.seed}})" >> $GITHUB_ENV
        else
          echo "seed=$(echo )" >> $GITHUB_ENV
        fi
    - run: python3 app/main.py --width=${{ inputs.width }} --height=${{ inputs.height }} ${{ env.print_solved }} ${{ env.print_unsolved }} ${{ env.export-solved }} ${{ env.export-unsolved }} ${{ env.seed }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: generated-maze
        path: ./*maze*.txt
